### PR TITLE
When parsing keys with spaces, no longer strip spaces from the middle

### PR DESCRIPTION
**Pull request by MichaelJJ**
This PR will resolve the situation where filenames have their spaces stripped.

As an example, currently the following INF section:
```
[SourceDisksFiles]
Dep With Space.txt = 1,,
```

Returns an Id value of: `DepWithSpace.txt`

This updated code should only strip whitespace from the start/end

### CODE REVIEW

**Comment by MichaelJJ** [comment]
@skalahonza Would it be possible to get a review?

**Comment by skalahonza** [comment]
> @skalahonza Would it be possible to get a review?

So sorry for the delay.
Missed this one in notifications.

**Review by skalahonza — CHANGES_REQUESTED** [review]
Again, sorry for the delay.
I ran the tests locally.
note: added CI for test automation

one test is failing
```cs
       [TestMethod()]
        public void CustomSerializationHugeDereferenceTest()
        {
            var helper = new InfUtil();
            foreach (var file in Directory.GetFiles(testFolder))
            {
                var serilized = helper.SerializeFileInto<DriverInfoDereferenced>(file, out InfData data);
                Assert.IsNotNull(serilized.Provider);
            }
        }
```

this test tries to parse all inf files for some common properties
all you have to do, is add this into the inf file you provided

```
[Version]
Class=somevalue
Provider=somevalue
```

**Comment by MichaelJJ** [comment]
@skalahonza Thanks for the details, the INF had Class, but I have added Provider.

**Review by skalahonza — APPROVED** [review]

**Comment by skalahonza** [comment]
@MichaelJJ published a new version with your changes
should appear soon
https://www.nuget.org/packages/InfHelper/0.10.1

**Pull request merged**
