### PR TITLE
Provide null entries for empty parts when KeyValue parsing

### LINKED ISSUE #14: Parser skips empty parts in Key/Value parsing, difficult to know which parts are populated
In a key value section, if some portions are empty, they are not reflected in the parsed output. This makes it difficult to determine which sections are actually provided. Is there a way to determine this, or should the parser be updated to provide null `KeyValues` entries for skipped portions?

As an example,

```
[SourceDisksNames]
1=%Disk1%,,,"sub-dir"
```

The parser provides only two `KeyValues` entries `%Disk1%` and `sub-dir`. I want to know what the "path" value is for this category. Unfortunately, there are also optional values after this directory, so I can't just use the final value.

This is the spec for this section:
`diskid = disk-description[,[tag-or-cab-file],[unused],[path],[flags][,tag-file]]`

If a user provided this:
```
[SourceDisksNames]
1=%Disk1%,,,"sub-dir","ab123"
```

I don't have a way to match up which values are provided, as the INF parser will provide only 3 entries in the object. If the `KeyValues` list provided a null for the empty separator sections, I should be able to figure it out in code.

### PR DESCRIPTION
**Pull request by MichaelJJ**
This will allow for reliable identification of values

### Goal
Closes #14

### Background
Some INF section entries have optional values. The current parsed INF object only returns sections that have a non-empty value. This makes it difficult to identify which optional sections have been skipped.

### Testing
Added a unit test

&nbsp;

Given the following INF entry:
```
[SourceDisksNames]
222=%DiskDescription%,,,\,flags
```

Before the change, the KeyValue entries would be: `[%DiskDescription%, \, flags]`

After the change, the entries would be: `[%DiskDescription%, null, null, \, flags]`

This helps in the situation in which I want to find the `path` entry, which is `\` in this case. Without the nulls, it is not possible to reliably get this section.

### CODE REVIEW

**Review by skalahonza — APPROVED** [review]

**Comment by skalahonza** [comment]
@MichaelJJ I created a release with your changes
https://www.nuget.org/packages/InfHelper/0.12.1

**Comment by skalahonza** [comment]
@MichaelJJ 
Hi i just wanted to ask in what context you use this library? Just out of curiosity. I am collecting real world use case examples.

**Comment by MichaelJJ** [comment]
> @MichaelJJ Hi i just wanted to ask in what context you use this library? Just out of curiosity. I am collecting real world use case examples.

We develop Windows drivers and use the library to parse and then validate the content of the INF file. The primary reason for using this library is so that we can run within a Linux container, as the .net native API calls are supported only on Windows.

**Comment by skalahonza** [comment]
> > @MichaelJJ Hi i just wanted to ask in what context you use this library? Just out of curiosity. I am collecting real world use case examples.
> 
> 
> 
> We develop Windows drivers and use the library to parse and then validate the content of the INF file. The primary reason for using this library is so that we can run within a Linux container, as the .net native API calls are supported only on Windows.

@MichaelJJ noticed that your email ends with Intel.com. Do you use this library as part of some Intel solution? I am asking because that would be a very cool reference for this small package 😁

**Pull request merged**
